import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { Cat, FeedingEvent, FeedingPlan, Food } from '@/domain/types';
import { getActivePlan } from '@/db/repositories/plans';
import { getFoodsByIds } from '@/db/repositories/foods';
import { recentEvents } from '@/db/repositories/events';
import { vetExportSummary } from '@/domain/history';
import { minutesToTimeLabel } from '@/domain/schedule';
import { formatPortion, formatWeight, type UnitSystem } from '@/utils/units';
import { VET_DISCLAIMER } from '@/domain/calories';

export async function exportVetSummaryPdf({
  cat,
  unitSystem,
}: {
  cat: Cat;
  unitSystem: UnitSystem;
}): Promise<string> {
  const [plan, events] = await Promise.all([
    getActivePlan(cat.id),
    recentEvents(cat.id, 500),
  ]);
  const foodIds = new Set<string>();
  plan?.foods.forEach((food) => foodIds.add(food.foodId));
  plan?.scheduledMeals.forEach((meal) => {
    if (meal.foodId) foodIds.add(meal.foodId);
  });
  events.forEach((event) => foodIds.add(event.foodId));
  const foods = await getFoodsByIds(Array.from(foodIds));
  const foodsById = new Map(foods.map((food) => [food.id, food]));

  const summary = vetExportSummary(events, 30);
  const html = renderVetSummaryHtml({
    cat,
    unitSystem,
    plan,
    events: summary.events,
    foodsById,
    generatedAt: summary.generatedAt,
    averageDailyKcal: summary.averageDailyKcal,
    totalKcal: summary.totalKcal,
    totalEvents: summary.totalEvents,
    missedCount: summary.missedCount,
  });

  const result = await Print.printToFileAsync({
    html,
    base64: false,
  });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(result.uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${cat.name} Whiskr vet summary`,
      UTI: 'com.adobe.pdf',
    });
  }

  return result.uri;
}

function renderVetSummaryHtml({
  cat,
  unitSystem,
  plan,
  events,
  foodsById,
  generatedAt,
  averageDailyKcal,
  totalKcal,
  totalEvents,
  missedCount,
}: {
  cat: Cat;
  unitSystem: UnitSystem;
  plan: FeedingPlan | null;
  events: FeedingEvent[];
  foodsById: Map<string, Food>;
  generatedAt: number;
  averageDailyKcal: number;
  totalKcal: number;
  totalEvents: number;
  missedCount: number;
}) {
  const planRows = plan?.scheduledMeals.length
    ? plan.scheduledMeals
        .map((meal) => {
          const food = meal.foodId ? foodsById.get(meal.foodId) : null;
          return `<tr><td>${minutesToTimeLabel(meal.timeOfDayMin)}</td><td>${escapeHtml(
            food ? `${food.brand} ${food.name}` : 'Food not found',
          )}</td><td>${Math.round(meal.kcalTarget)} kcal</td></tr>`;
        })
        .join('')
    : '<tr><td colspan="3">No active feeding plan saved.</td></tr>';

  const eventRows = events.length
    ? events
        .slice()
        .reverse()
        .map((event) => {
          const food = foodsById.get(event.foodId);
          const date = new Date(event.fedAt);
          return `<tr><td>${escapeHtml(date.toLocaleString())}</td><td>${escapeHtml(
            food ? `${food.brand} ${food.name}` : 'Food not found',
          )}</td><td>${formatPortion(event.amountG, unitSystem)}</td><td>${Math.round(
            event.kcal,
          )} kcal</td><td>${escapeHtml(event.status)}</td></tr>`;
        })
        .join('')
    : '<tr><td colspan="5">No feeding events logged in the last 30 days.</td></tr>';

  return `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1C1916; padding: 32px; }
      h1 { font-size: 30px; margin: 0 0 4px; }
      h2 { font-size: 18px; margin: 28px 0 10px; }
      p { line-height: 1.45; }
      .muted { color: #6B625A; }
      .grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; margin-top: 18px; }
      .card { border: 1px solid #EDE6DC; border-radius: 14px; padding: 14px; background: #FAF6F0; }
      .label { color: #6B625A; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; }
      .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
      table { border-collapse: collapse; width: 100%; margin-top: 8px; }
      th, td { border-bottom: 1px solid #EDE6DC; padding: 9px 6px; text-align: left; vertical-align: top; }
      th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: #6B625A; }
      footer { margin-top: 28px; font-size: 12px; color: #6B625A; }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(cat.name)} feeding summary</h1>
    <p class="muted">Generated by Whiskr on ${escapeHtml(new Date(generatedAt).toLocaleString())}</p>

    <div class="grid">
      <div class="card"><div class="label">Weight</div><div class="value">${formatWeight(cat.weightKg, unitSystem)}</div></div>
      <div class="card"><div class="label">Daily target</div><div class="value">${Math.round(cat.mealGoalKcal)} kcal</div></div>
      <div class="card"><div class="label">Body condition</div><div class="value">${cat.bodyCondition}/9</div></div>
      <div class="card"><div class="label">Activity</div><div class="value">${escapeHtml(cat.activityLevel)}</div></div>
    </div>

    <h2>30-day snapshot</h2>
    <div class="grid">
      <div class="card"><div class="label">Average daily intake</div><div class="value">${Math.round(averageDailyKcal)} kcal</div></div>
      <div class="card"><div class="label">Total logged kcal</div><div class="value">${Math.round(totalKcal)} kcal</div></div>
      <div class="card"><div class="label">Logged events</div><div class="value">${totalEvents}</div></div>
      <div class="card"><div class="label">Skipped/missed</div><div class="value">${missedCount}</div></div>
    </div>

    <h2>Current feeding plan</h2>
    <table>
      <thead><tr><th>Time</th><th>Food</th><th>Target</th></tr></thead>
      <tbody>${planRows}</tbody>
    </table>

    <h2>Recent feeding events</h2>
    <table>
      <thead><tr><th>Date</th><th>Food</th><th>Amount</th><th>Kcal</th><th>Status</th></tr></thead>
      <tbody>${eventRows}</tbody>
    </table>

    <footer>
      ${escapeHtml(VET_DISCLAIMER)}
    </footer>
  </body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
